### ISSUE TITLE
README

### ISSUE THREAD

**Issue by nahharris** [auralangco/aurac#2]
Write a better Readme with some images and more info about the project

**Comment by aarabii** [comment]
Hey @OJarrisonn i would like to try to update the readme for you if you want me to...
for this can you provide me details, user cases and everything else you think is necessary....

**Comment by nahharris** [comment]
It would be really helpful

Some more details about Aura lang it self can be chrckout out [here](https://github.com/auralangvo/aura).

About aurac itself i don't have much to say. It's a compiler for aura that targets C.  The idea in the alpha stage is to write the IR directly in rust code and then produce C code (non legible) to execute it.

For the future i plan:

- a front end to properly compile aura code into C
- a wrapper for gcc/clang/mingw so aurac compiles the code to C and then to a executable
- easy interop with C native code
- add targets for JS and C for windows

Also if you could incluse some badges (stars, current release, etc) in the readme it'd be cool. I'm still thinking about the visual identity of the Aura project (maybe white with yellowish/golden as accent)

**Comment by aarabii** [comment]
Hey @OJarrisonn sorry i was kinda busy with some personal issues so haven't got time to respond but i staed working on your readme just give me few hours

**Comment by nahharris** [comment]
No problem, take your time

**Comment by aarabii** [comment]
Hey @OJarrisonn can you share how we can install or use in our local machine or some screen shorts or code snipits of your language it will be wonder full to add them of readme 
if you got Discord it would be worder full to ask you more question relatwed to your repo

**Comment by nahharris** [comment]
Well, Aura still in early stages so there is currently no installation method, but i have some example code [here](https://github.com/auralangco/aura/blob/master/examples/core.aura)

Also just created a [discord server](https://discord.gg/JDc6Yj2dEM) for Aura (please notice the server is completly new and empty)
